<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Access\Module'                        => __DIR__ . '/Module.php',
    'Access\Controller\SkeletonController' => __DIR__ . '/src/Access/Controller/SkeletonController.php',
    'AccessTest\Framework\TestCase'        => __DIR__ . '/tests/Access/Framework/TestCase.php',
    'AccessTest\SampleTest'                => __DIR__ . '/tests/Access/SampleTest.php',
);
